config/routes.rb
Rails.application.routes.draw do

  get 'scraper/get' => 'scraper#get'
  get 'wordnik/get' => 'wordnik#get'
  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'matches/:title' => 'matches#index'
  get 'links/:title' => 'links#matches'

    get 'users/graphs' => 'graphs#all'
  resources :users do
    get 'react/:id' => 'graphs#react', as: 'react'
    resources :graphs do
      resources :ideas
      get 'react/:id' => 'ideas#react', as: 'react_ideas'
    get 'redirect_to/:idea_id' => 'graphs#redirect'
      resources :links
    end
  end

  root 'graphs#index'

end

app/models/graph.rb
# == Schema Information
#
# Table name: graphs
#
#  id          :integer          not null, primary key
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  description :string
#  public      :boolean          default(FALSE)
#  private     :boolean          default(FALSE)
#

class Graph < ActiveRecord::Base
  has_many :ideas, dependent: :destroy
  belongs_to :user
  validates :title, presence: true
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_action :set_graph, only: [:show, :redirect, :update, :destroy, :edit, :update, :react]

  def index
    @graphs = current_user.graphs
  end

  def user_edit
    @graphs = current_user.graphs
    @user = current_user
  end

  def edit
  end

  def update
    if @graph.update(graph_params)
      redirect_to user_graphs_path, notice: 'Tambi was successfully updated.'
    else
      render :edit
    end
  end

  def all
    @graphs = (Graph.order(id: :desc) - current_user.graphs).reject{|g| g.private }
  end

  def show
    redirect_to user_graph_ideas_path(graph_id: @graph.id)
  end

  def react
    redirect_to user_graph_react_ideas_path(graph_id: @graph.id)
  end

  def redirect
    @path = user_graph_ideas_path(graph_id: @graph)
  end

  def create
    @graph = current_user.graphs.new(graph_params)
    if @graph.save
      create_first_idea(@graph.title)
      redirect_to user_graph_ideas_path(graph_id: @graph.id)
    else
      redirect_to user_graphs_path, alert: 'Something has gone wrong'
    end
  end

  def destroy
    @graph.destroy
    redirect_to user_graphs_path , notice: 'Graph was successfully destroyed.'
  end

  private

  def create_first_idea(first_title)
      first_title ||= 'Idea'
      concept = Concept.find_by_title( first_title ) || Concept.create(title: first_title )
      Idea.create(  graph_id: @graph.id,
                    x: 600,
                    y: 400,
                    font_size: 20,
                    concept_id: concept.id,
                    concept_type: 'concept')
  end

  def set_graph
    @graph = params[:idea_id] ? Graph.find(Idea.find(params[:idea_id]).graph.id) : Graph.find(params[:id])
  end

  def graph_params
    params.require(:graph).permit(:title, :user_id, :description, :public, :private)
  end
end

app/views/graphs/_form.html.erb
<% graph =  @graph || Graph.new %>
<%= simple_form_for([current_user, graph])  do |f| %>
  <% if graph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(graph.errors.count, "error") %> prohibited this graph from being saved:</h2>

      <ul>
      <% graph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.input :title, :placeholder=>"New Tambi"%>
    <%= f.input :description,:as =>'text', :placeholder=>"Short description of the Tambi"%>
    <%= f.input  :public, label: 'Make it collaborative' %>
    <%= f.input  :private, label: 'Make it private' %>
    <%= link_to 'Back', :back, class: 'btn btn-default' if @graph %>
    <%= f.submit text, :class=>'btn btn-success vertical-center' %>
<% end %>

app/views/graphs/all.html.erb
<div id="empty"></div>
<div class="container">
  <h1>Tambis Feed</h1>
    <% @graphs.each do |graph| %>
      <div class="panel panel-default col-md-3 thumbnail feed">
        <div class="panel-body">
          <%= link_to user_graph_path(user_id: graph.user, id: graph) do %>
             <h3><%= graph.title %></h3>
           <% end %>
          <h5><em><%= graph.user.username %></em></h5>
          <h6><em><%= 'Collaborative' if graph.public %></em></h6>
          <div><%= graph.description %></div>
        </div>
      </div>
    <% end %>
</div>

app/views/graphs/edit.html.erb
<div id="empty"></div>
<div class="container">
  <h1>Edit your Tambi info</h1>

  <%= render 'form', text: 'Update' %>
</div>

app/views/graphs/index.html.erb
<div id="empty"></div>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">Profile</div>
          <div class="panel-body">
            <div class="row">
              <div class="col-md-4 col-xs-12">
                <%= image_tag(current_user.image.url(:thumb), class: "img-avatar") %>
              </div>
              <div class="col-md-8 col-xs-12">
                <h6>Username</h6>
                <h4><%= current_user.username %></h4>
              </div>
            </div>
            <div class="row">
              <h6>Bio</h6>
              <h5><%= current_user.bio %></h5>
            </div>
          </div>
        </div>
     </div>
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">Your Tambis</div>
         <div class="panel-body">
          <ul class="list-group">
            <% @graphs.each do |graph| %>
                <li class="list-group-item">
              <%= link_to user_graph_path(user_id: current_user, id: graph) do %>
                  <%= graph.title %>
              <% end %>
                  <small><strong><%= 'Collaborative' if graph.public %></strong></small>
                  <small><strong><%= 'Private' if graph.private %></strong></small>
                  <%= link_to( user_graph_path(user_id: current_user, id: graph) ,{ confirm: "Are you sure you want to delete this canvas?", method: :delete, :class => 'badge'}) do %>
                    <i class="fa fa-trash-o"></i>
                  <% end %>
                  <%= link_to( edit_user_graph_path(user_id: current_user, id: graph) , { class: 'badge'}) do %>
                    <i class="fa fa-pencil"></i>
                  <% end %>
                  <span class='small' ><%= graph.description %></span>
                </li>
            <% end %>
          </ul>
          <div class="panel panel-default">
            <div class="panel-heading">Create a new Tambi</div>
              <div class="panel-body">
                <%= render 'form', text: 'Create' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/graphs/user_edit.html.erb
<div id="empty"></div>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">Profile</div>
          <div class="panel-body">
            <%= simple_form_for(@user) do |f| %>
              <%= f.error_notification %>
              <p>Image</p>
              <p>Name</p>
                <%= f.input :username, required: true, autofocus: true %>
              <p>Bio</p>
                <%= f.input :bio, autofocus: true %>
                <%= link_to 'Back', user_graphs_path(current_user), :class => 'btn btn-default' %>
                <%= f.button :submit, "Save" %>
            <% end %>
          </div>
        </div>
     </div>
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">Your Tambis</div>
         <div class="panel-body">
          <ul class="list-group">
            <% @graphs.each do |graph| %>
              <%= link_to user_graph_path(user_id: current_user, id: graph) do %>
                <li class="list-group-item">
                  <%= graph.title %>
                  <%= link_to user_graph_path(user_id: current_user, id: graph), :class => 'badge', :confirm => "Are you sure you want to delete this canvas?", :method => :delete do %>
                    <i class="fa fa-times"></i>
                  <% end %>
                  <span class='small' ><%= graph.description %></span>
                </li>
              <% end %>
            <% end %>
          </ul>
          <div class="panel panel-default">
            <div class="panel-heading">Create a new Tambi</div>
              <div class="panel-body">
                <%= render 'form' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>