config/routes.rb
Rails.application.routes.draw do

  get 'scraper/get' => 'scraper#get'
  get 'wordnik/get' => 'wordnik#get'
  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'matches/:title' => 'matches#index'
  get 'links/:title' => 'links#matches'

    get 'users/graphs' => 'graphs#all'
  resources :users do
    get 'react/:id' => 'graphs#react', as: 'react'
    resources :graphs do
      resources :ideas
      get 'react/:id' => 'ideas#react', as: 'react_ideas'
    get 'redirect_to/:idea_id' => 'graphs#redirect'
      resources :links
    end
  end

  root 'graphs#index'

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "TAMBI-logo-black.png" %>
      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if @graph %>
             <!-- <li><a>Search<input></input></a><li> -->
            <li> <a><em><%= @graph.title %></em></a>  </li>
          <% end %>
            <li><%= link_to "My Tambis", user_graphs_path(current_user) %></li>
            <li><%= link_to "Feed", users_graphs_path %></li>
            <% if current_user.graphs.last %>
              <li><%= link_to "React", user_react_path( user_id: current_user.id , id: current_user.graphs.last ) %></li>
            <% end %>
            <li class="dropdown">
              <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %> Settings <span class="caret"></span> <% end %>
              <ul class="dropdown-menu" role="menu">
                <li><a id='show-instructions'><i class="fa fa-info-circle" ></i> Info</a></li>
                <li><a id='open-toolbox'><i class="fa fa-magic"></i> Toolbox</a></li>
                <li><%= link_to edit_user_registration_path do %><i class="fa fa-user"></i> Edit Profile<% end %></li>
                <li><%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out"></i><%= t ".sign_out", default: "Sign out" %>
                <% end %></li>
              </ul>
            </li>
        <% else %>
         <!--  <li>
            <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path %>
          </li> -->
          <li>
            <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>